### ISSUE TITLE
Please support warp 3.3.5?

### ISSUE THREAD

**Issue by peti** [haskell-servant/servant-blaze#17]
Would it be possible to get an update for `servant-blaze` that supports the current version of `warp-3.3.5`? I tried the build with the upper bound edited out and it succeeded just fine, so maybe all there is to it is to edit the Cabal file an Hackage to allow the newer version.

**Comment by phadej** [comment]
warp is a test dependency, how it affect you?

Will do when updating non-library bounds, hopefully will do servant-0.17 release early 2020

**Comment by peti** [comment]
> warp is a test dependency, how it affect you?

Nix builds the tests of every Haskell package by default. We got build errors because of the over-specified dependency.

**Comment by phadej** [comment]
Please, `dontCheck` `servant-blaze`

**Comment by peti** [comment]
https://github.com/NixOS/nixpkgs/commit/fdd64fbc3730f44573d1a86928b63fba421ba287

**Comment by maksbotan** [comment]
Seems to be fixed in commit 109084f1.
